apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-applocation
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Andr1500/argocd-app-config.git
    targetRevision: HEAD #last commitfrom the repo
    path: dev

  destination:
    server: https://kubernetes.default.svc #endpoint of k8s api server
    namespace: myapp #if it doesn't exist, argo will creae it

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true #automatically revert changes in case of any manual changes
      prune: true
